server:
  port: 8090

spring:
  application:
    name: spring-cloud-gateway

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
